FROM python:3.11-slim as backend-builder

RUN pip install poetry==1.8.2

ENV POETRY_VIRTUALENVS_IN_PROJECT=true \
    POETRY_CACHE_DIR='/tmp/poetry_cache_keytokens_analysis' \
    TRANSFORMERS_CACHE='/tmp/transformers_cache'

WORKDIR /app

RUN touch README.md

COPY backend/pyproject.toml backend/poetry.lock ./
RUN --mount=type=cache,target=${POETRY_CACHE_DIR} \
    poetry install --no-root --without dev,test

COPY backend/infra/scripts/save_models.py ./
RUN --mount=type=cache,target=${TRANSFORMERS_CACHE} \
     poetry run python -m save_models

FROM python:3.11-slim

ENV VIRTUAL_ENV='/app/.venv' \
    AI_MODELS='/app/saved_models' \
    PATH=/app/.venv/bin:$PATH

WORKDIR /app

COPY --from=backend-builder ${AI_MODELS} ${AI_MODELS}
COPY --from=backend-builder ${VIRTUAL_ENV} ${VIRTUAL_ENV}

COPY ./backend/data ./data
COPY ./backend/domain ./domain
COPY ./backend/infra ./infra

CMD uvicorn infra.http.main:app --host 0.0.0.0 --port 80 --log-level warning
